multiple_runs

diff --git a/sbatch_scripts/kernel_processing.sbatch.template b/sbatch_scripts/kernel_processing.sbatch.template
--- a/sbatch_scripts/kernel_processing.sbatch.template
+++ b/sbatch_scripts/kernel_processing.sbatch.template
@@ -14,10 +14,17 @@
 
 NPROC=$SLURM_NTASKS
 
-mpirun --rank-by core -np $NPROC ./bin.kernel/xsum_kernels :event_file: :output_file:
+mpirun --rank-by core -np $NPROC ./bin.kernel/xsum_kernels :event_file: :output_file: :model_file:
 
 if [ $? -ne 0 ]; then
 echo " Error in Kernel_Sum"
+exit 1
+fi
+
+mpirun --rank-by core -np $NPROC ./bin.kernel/xsrc_mask :KERNEL_FILE: :MASK_DIRS_FILE: :OUTPUT_FILE_MASK:
+
+if [ $? -ne 0 ]; then
+echo " Error in Kernel_Masking"
 exit 1
 fi
 
