update subroutines

diff --git a/sbatch_scripts/kernel_processing.sbatch.template b/sbatch_scripts/kernel_processing.sbatch.template
--- a/sbatch_scripts/kernel_processing.sbatch.template
+++ b/sbatch_scripts/kernel_processing.sbatch.template
@@ -22,18 +22,17 @@ echo " Error in Kernel_Sum"
 exit 1
 fi
 
-
-:mpibin: $NPROC :kernel_mask_bin: :kernel_parfile: :KERNEL_FILE: :MASK_DIRS_FILE: :OUTPUT_FILE_MASK:
-
-if [ $? -ne 0 ]; then
-echo " Error in Kernel_Masking"
-exit 1
-fi
-
-
 :mpibin: $NPROC :kernel_smooth_bin: :SIGMA_H: :SIGMA_V: :KERNEL_NAME: :INPUT_FILE: :SOLVER_FILE: :OUTPUT_FILE: :GPU_MODE:
 
 if [ $? -ne 0 ]; then
 echo " Error in Kernel_Smoothing"
+exit 1
+fi
+
+
+:mpibin: $NPROC :kernel_invhess_bin: :kernel_parfile: :KERNEL_FILE: :OUTPUT_FILE_HESS: :INVHESS_THRESHOLD:
+
+if [ $? -ne 0 ]; then
+echo " Error in Kernel Inverse Hessian"
 exit 1
 fi
